use super::{DefaultKind, KindId, SubKind};

/// Bind the token kind value with an [`KindId`].
///
/// This is readonly to make sure the binding is not broken,
/// you can use [`Self::take`] to take the kind value out.
/// # Examples
/// ```
/// use whitehole::lexer::token::{kind, KindIdBinding, SubKind};
///
/// #[kind]
/// #[derive(Debug)]
/// enum MyKind { A, B(i32) }
/// // struct `A` and `B` will be generated by the macro
///
/// # fn main() {
/// let a: KindIdBinding<MyKind> = A.into();
/// let b: KindIdBinding<MyKind> = B(0).into();
/// assert_eq!(a.id(), A::kind_id());
/// assert_eq!(b.id(), B::kind_id());
/// assert!(matches!(a.kind(), MyKind::A));
/// assert!(matches!(b.kind(), MyKind::B(B(0))));
/// # }
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct KindIdBinding<Kind> {
  id: KindId<Kind>,
  kind: Kind,
}

// this is the only way to construct self
impl<Kind, ViaKind: SubKind<Kind = Kind> + Into<Kind>> From<ViaKind> for KindIdBinding<Kind> {
  #[inline]
  fn from(value: ViaKind) -> Self {
    Self {
      id: ViaKind::kind_id(),
      kind: value.into(),
    }
  }
}

impl<Kind> KindIdBinding<Kind> {
  /// Get the id of the sub token kind.
  /// See [`KindId`].
  #[inline]
  pub const fn id(&self) -> KindId<Kind> {
    self.id
  }

  /// Get the value of the token kind.
  #[inline]
  pub const fn kind(&self) -> &Kind {
    &self.kind
  }

  /// Consume self and take the kind value out.
  #[inline]
  pub fn take(self) -> Kind {
    self.kind
  }
}

impl<Kind: DefaultKind + Default> Default for KindIdBinding<Kind> {
  #[inline]
  fn default() -> Self {
    Self {
      id: Kind::default_kind_id(),
      kind: Kind::default(),
    }
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use whitehole_macros::_kind;

  #[_kind]
  #[derive(Debug, PartialEq, Default)]
  enum MyKind {
    #[default]
    A,
  }

  #[test]
  fn kind_id_binding() {
    let binding: KindIdBinding<_> = A.into();
    assert_eq!(binding.id(), A::kind_id());
    assert_eq!(binding.kind(), &MyKind::A);
    assert_eq!(binding.take(), MyKind::A);
  }

  #[test]
  fn default_kind_id_binding() {
    let binding = KindIdBinding::<MyKind>::default();
    assert_eq!(binding.id(), MyKind::default_kind_id());
    assert_eq!(binding.take(), MyKind::default());
  }
}
