name: Coverage

on: workflow_dispatch

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo install cargo-tarpaulin

      - run: cargo tarpaulin --out Xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: DiscreteTom/whitehole
          fail_ci_if_error: true
